### PR TITLE
script: fix unused variable warnings

### PR DESCRIPTION
**Pull request by TheLavaBlock**
if you have set warnings as errors, it causes problems

### CODE REVIEW

**Comment by ziga-lunarg** [comment]
@TheLavaBlock thanks for the fix. You should also build the layer with these changes and include them in the PR.

**Comment by TheLavaBlock** [comment]
Here we go...

btw: [BUILD.md](https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/BUILD.md#linux-and-macos-build) is not up-to-date and unfortunately also contains error :eyes:

**Comment by ziga-lunarg** [comment]
> Here we go...
> 
> btw: [BUILD.md](https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/BUILD.md#linux-and-macos-build) is not up-to-date and unfortunately also contains error 👀

Do you see anything other than `cd VulkanTools` instead of `cd Vulkan-Profiles`?

**Comment by TheLavaBlock** [comment]
yeah that's the error and I think `git@github.com:LunarG/VulkanProfiles.git` is no longer up to date, right?

**Comment by ziga-lunarg** [comment]
Will be fixed in #183 , thanks!

**Pull request merged**
