### PR TITLE
ci: Add iOS build to CI

### PR DESCRIPTION
**Pull request by juan-lunarg**
closes https://github.com/LunarG/Projects/issues/714

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
@juan-lunarg does it mean we want to support the Profiles layer on iOS? @richard-lunarg ?

**Comment by richard-lunarg** [comment]
Yes, we do want to support Profiles on iOS. Do you not see value in this?

**Comment by christophe-lunarg** [comment]
@richard-lunarg  I can see value, it's more whether we have a plan to see the priority and the focus I should consider on this or not.

**Comment by juan-lunarg** [comment]
> @richard-lunarg I can see value, it's more whether we have a plan to see the priority and the focus I should consider on this or not.

For now the plan is that MacOS testing should be enough to cover iOS testing. So it shouldn't require much if any work from profiles.

**Pull request merged**
