### PR TITLE
profiles: Update utility libraries to v1.3.251

### PR DESCRIPTION
**Pull request by juan-lunarg**

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Actually, I used main on purpose to be able to catch issues in the Utility-Liabaries repository following the spirit of the validation layer using profiles main to catch issues.

**Comment by juan-lunarg** [comment]
> Actually, I used main on purpose to be able to catch issues in the Utility-Liabaries repository following the spirit of the validation layer using profiles main to catch issues.

We use main in `common_ci.py` which only affects testing. `known_good.json` should always produce a stable build.

**Comment by christophe-lunarg** [comment]
Ah ok then.

**Comment by juan-lunarg** [comment]
Also in `common_ci.py` we aren't grabbing dependencies required to build the validation layers. We are grabbing binary dependencies required to enable testing.

**Pull request merged**
