### PR TITLE
profiles layer: Skip loading structs from excluded extensions

### LINKED ISSUE #96: Layer: Excluded extensions are not reported?
image

i would expect at least a warning or notification that say that we are excluding an extension that is required by the selected profile.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #96

### CODE REVIEW

**Comment by aqnuep** [comment]
Some of these aren't just extension structures, but ones that also got promoted to core versions, e.g. `VkPhysicalDeviceMaintenance3Properties`.

Is it intended to skip these structures if the core API version would include them even without the excluded extensions?

**Comment by christophe-lunarg** [comment]
it's not clear to me what this PR is doing. i build the branch and tried it:
profiles_excluded_ext

```
PROFILES WARNING: shaderDrawParameters JSON value is enabled in the profile, but the device does not support it.
```
Is still appearing...
And we don't get any notification regarding the features of `VK_KHR_8bit_storage` that is excluded and in the profile so it's not clear for the Vulkan developer to understand what's going on. 

I think the exclude settings should override the profile but this should be notified to the Vulkan developer (not only in the settings notification, but in how the settings are effectively executed).

**Comment by ziga-lunarg** [comment]
@aqnuep I'm not sure what I should do there, it probably shouldn't be excluded

**Comment by ziga-lunarg** [comment]
@christophe-lunarg Added the logs now

**Pull request closed without merging**
